spring:
  application:
    name: bot
  kafka:
    bootstrapServers: kafka:9092
    consumer:
      group-id: tgbotGroup
      topic: vacation

server:
  port: 8079

bot:
  name: StasintTest1Bot
  token: 8492288942:AAEC9nn5nQt1Ab8SzsS25nrtilmM7xvO2lc

hazelcast:
  endpoint: hazelcast:5701
  cluster_name: "dev"
  map_name: "chat-state-map"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        loggerLevel: basic

url:
  employee: http://employee:8080/api/v1
  vacation: http://vacation:8081/api/v1
